Add all controlers
-  rename `spigot-listener` instead of `spigot-idle`
-  add `async-runner` for signal-friendly command
-  add `decisiontab` for decision table
-  add `event-fsm` for event-driven finite state machine
-  add `event-timer-ugly` for event notification timer

diff --git a/rootfs/usr/local/bin/echo-fail b/rootfs/usr/local/bin/echo-fail
--- a/rootfs/usr/local/bin/echo-fail
+++ b/rootfs/usr/local/bin/echo-fail
@@ -1,8 +1,7 @@
 #!/bin/sh
 
-LIGHT_RED='\033[1;31m'
-NC='\033[0m'
+set -euo pipefail
 
-echo -ne "[${LIGHT_RED}FAIL${NC}]${1:+ }"
-echo "${@}"
-exit 1
+source /usr/local/etc/color.conf
+
+echo -e "[$(date '+%H:%M:%S') ${RED}FAIL${NC}]${1:+: }${@}"
diff --git a/rootfs/usr/local/bin/spigot-backup b/rootfs/usr/local/bin/spigot-backup
--- a/rootfs/usr/local/bin/spigot-backup
+++ b/rootfs/usr/local/bin/spigot-backup
@@ -10,15 +10,24 @@ function exit_with_result() {
             echo-pass "Backup completed"
             ;;
         *)
-            echo-fail "Failed to backup"
+            echo-fail "Backup aborted"
+            exit 1
             ;;
     esac
 }
 
-echo-info "Starting backup..."
+function file_size() {
+    echo "$(stat -c '%s' "${1}") bytes"
+}
+
+function backups() {
+    ls -1 "${BACKUP_DIR}"/${BACKUP_PATTERN}
+}
+
+echo-info "Backup started"
 trap exit_with_result EXIT
 
-BACKUP_FILE="${BACKUP_DIR}/$(date "+${BACKUP_FILE_FORMAT}")"
+BACKUP="${BACKUP_DIR}/$(date "+${BACKUP_FORMAT}")"
 
 if [ -e "${RESTORE_STATUS_FILE}" ]
 then
@@ -29,12 +38,24 @@ fi
 
 tar \
 -cz \
--f "${BACKUP_FILE}" \
+-f "${BACKUP}" \
 -C "${DIRECTORY}" \
 "${BACKUP_FILES[@]}"
 
-echo-pass "${BACKUP_FILE}: Created"
+echo-info "${BACKUP}: Backup created ($(file_size "${BACKUP}"))"
 
-# TODO rotate backup
+if [ -n "${BACKUP_KEEP_NUMS}" ]
+then
+    OVER_NUMS=$(($(backups | wc -l) - ${BACKUP_KEEP_NUMS}))
+
+    if [ ${OVER_NUMS} -gt 0 ]
+    then
+        echo-info "${OVER_NUMS} backup(s) removing..."
+        backups | head -n "${OVER_NUMS}" | xargs rm -v
+        echo-info "${OVER_NUMS} backup(s) removed"
+    fi
+else
+    echo-info "$(backups | wc -l) backup(s) are never removed"
+fi
 
 RESULT=completed
diff --git a/rootfs/usr/local/bin/spigot-restore b/rootfs/usr/local/bin/spigot-restore
--- a/rootfs/usr/local/bin/spigot-restore
+++ b/rootfs/usr/local/bin/spigot-restore
@@ -13,16 +13,17 @@ function exit_with_result() {
             echo-pass "No backup"
             ;;
         *)
-            echo-fail "Failed to restore"
+            echo-fail "Restore aborted"
+            exit 1
             ;;
     esac
 }
 
 function last_backup() {
-    ls "${BACKUP_DIR}"/${BACKUP_FILE_PATTERN} 2> /dev/null | tail -n1
+    ls "${BACKUP_DIR}"/${BACKUP_PATTERN} 2> /dev/null | tail -n1
 }
 
-echo-info "Starting restore..."
+echo-info "Restore started"
 trap exit_with_result EXIT
 
 if [ ${#@} -eq 0 ]
@@ -38,9 +39,10 @@ fi
 
 if [ -e "${BACKUP}" ]
 then
-    echo-pass "${BACKUP}: Found"
+    echo-info "${BACKUP}: Backup found"
 else
-    echo-fail "${BACKUP}: Not found"
+    echo-fail "${BACKUP}: Backup not found"
+    exit 1
 fi
 
 (
